### ISSUE TITLE
Undefined symbol

### ISSUE THREAD

**Issue by cringeops** [cropinghigh/sdrpp-tetra-demodulator#17]
After the most recent commit, I get this error when trying to load the module:
`[ERROR] Couldn't load /usr/lib/sdrpp/plugins/tetra_demodulator.so: /usr/lib/sdrpp/plugins/tetra_demodulator.so: undefined symbol: _ZTVN3dsp4loop15PI4DQPSK_COSTASE`

It works fine when I checkout to the previous commit (206ab9f60861faa5b145e04ba9610206d23dec26).

**Comment by cropinghigh** [comment]
Try doing cmake .. in build folder again

**Comment by autodiag** [comment]
> Zkuste to cmake .. znovu ve složce sestavení

I deleted the build address bar and then cmake... & make

**Comment by cropinghigh** [comment]
Sorry... forgot to add cmakelists to git commit. Fixed by [906e5ce](https://github.com/cropinghigh/sdrpp-tetra-demodulator/commit/906e5ce36f3e484551562fa0229137d4cccc5cfb)

**Comment by autodiag** [comment]
> Sorry... forgot to add cmakelists to git commit. Fixed by [906e5ce](https://github.com/cropinghigh/sdrpp-tetra-demodulator/commit/906e5ce36f3e484551562fa0229137d4cccc5cfb)

yes work now
little bug to CC code: all is decimal but CC code  is hexa ;) ..

maybe I will invent but it seems logical to me that if there is already an audio codec in the demodulator module (eight meter), then it would be good to add information about GSSI and ISSI of the ongoing call to the plugin (which could be parsed using a text file) or other information similar to the plugins for SDRSharp or even in this module to make the output of data to decode them into a UDP socket. ..that's why there was a request to output raw data that could be further processed, which yes works in the netsyms module, but it is again necessary to have it in several windows including the audio codec

Otherwise I have to say that the plugin works absolutely great, it is fast and the audio performance is very good, thank you for it

**Comment by cringeops** [comment]
The issue is resolved
